package eu4SaveReader.Utils;

import java.util.HashMap;

public final class Policies {
	
	private Policies() {}
	
	public static final HashMap<String, String> policies = new HashMap<>();
	static {
		policies.put("agricultural_cultivations", "Agricultural Cultivation");
		policies.put("anti_heresy_act", "Anti-Heresy Act");
		policies.put("anti_smuggling_act", "Anti-Smuggling Act");
		policies.put("armed_neutrality_act", "Armed Neutrality Act");
		policies.put("autonomous_estates", "Autonomous Estates");
		policies.put("the_banking_system", "Banking System");
		policies.put("beneficial_neglect", "Benign Neglect");
		policies.put("black_chamber_act", "Black Chamber Act");
		policies.put("chaplains_of_the_fleet", "Chaplains of the Fleet");
		policies.put("cloth_quality_edict", "Cloth Quality Edict");
		policies.put("colonial_administration_act", "Colonial Administration Act");
		policies.put("colonial_companies_act", "Colonial Companies Act");
		policies.put("colonial_expansions", "Colonial Expansion");
		policies.put("colonial_garrisons", "Colonial Garrisons");
		policies.put("restrictions_for_colonies", "Colonial Restrictions");
		policies.put("the_combination_act", "Combination Act");
		policies.put("commercial_embassies", "Commercial Embassies");
		policies.put("the_cooperation_act", "Cooperation Act");
		policies.put("the_court_of_wards_and_liveries", "Court of Wards and Liveries");
		policies.put("cultural_recognition_act", "Cultural Recognition Act");
		policies.put("cultural_understanding", "Cultural Understanding");
		policies.put("cultural_unity", "Cultural Unity");
		policies.put("deserteur_act", "Deserter Act");
		policies.put("diplomatic_cooperation_act", "Diplomatic Cooperation");
		policies.put("diplomatic_defence_act", "Diplomatic Defense Act");
		policies.put("the_dissolution_act", "Dissolution Act");
		policies.put("edict_of_expulsion", "Edict of Expulsion");
		policies.put("the_education_act", "Education Act");
		policies.put("encouragement_of_merchant_navy", "Encouragement of Merchant Navy");
		policies.put("enforce_religious_law", "Enforce Religious Law");
		policies.put("enlightened_aristocracy", "Enlightened Aristocracy");
		policies.put("the_espionage_act", "Espionage Act");
		policies.put("exchange_of_ideas", "Exchange of Ideas");
		policies.put("the_field_agent_act", "Field Agent Act");
		policies.put("field_priests", "Field priests and Soldier's prayer books");
		policies.put("fleet_surgeons", "Fleet Surgeons");
		policies.put("foreign_advisors", "Foreign Advisors");
		policies.put("the_foreign_aid_act", "Foreign Aid Act");
		policies.put("the_foreign_support_act", "Foreign Support Act");
		policies.put("formalized_measures", "Formalized Scales, Weights and Measures");
		policies.put("fortified_trading_posts", "Fortified Trading Posts");
		policies.put("full_sovereignty_act", "Full Sovereignty Act");
		policies.put("the_garrison_act", "Garrison System");
		policies.put("guerilla_warfare", "Guerilla Warfare");
		policies.put("harbour_administration", "Harbor Administration");
		policies.put("hired_adventurers_act", "Hired Adventurers");
		policies.put("horse_artillery", "Horse Artillery");
		policies.put("the_importation_act", "Importation Act");
		policies.put("inspirational_leaders", "Inspirational Leaders");
		policies.put("the_integrated_administration_act", "Integrated Administration Act");
		policies.put("land_inheritance_act", "Land Inheritance Act");
		policies.put("letters_of_marque", "Letters of Marque");
		policies.put("the_liberation_act", "Liberation Act");
		policies.put("the_licensing_of_the_press_act", "Licensing of the Press Act");
		policies.put("the_liquor_act", "Liquor Act");
		policies.put("local_army_organisation", "Local Army Organization");
		policies.put("local_militias", "Local Militias");
		policies.put("manueline_architecture", "Manueline Architecture");
		policies.put("the_mercenary_registration_act", "Mercenary Registration Act");
		policies.put("messenger_ships", "Messenger Ships");
		policies.put("military_zeal_act", "Military Zeal Act");
		policies.put("the_mining_act", "Mining Act");
		policies.put("modern_firearm_techniques", "Modern Firearm Techniques");
		policies.put("modern_siege_weapons", "Modern Siege Weapons");
		policies.put("multilingual_diplomats", "Multilingual Diplomats");
		policies.put("native_assimilation_act", "Native Assimilation Act");
		policies.put("the_nautic_education_act", "Nautical Education Act");
		policies.put("convoy_system", "Naval Convoy System");
		policies.put("naval_infrastructure_act", "Naval Infrastructure");
		policies.put("the_naval_inspection_act", "Naval Inspection Act");
		policies.put("naval_school_act", "Naval School Act");
		policies.put("naval_secrecy_act", "Naval Secrecy Act");
		policies.put("the_naval_supremacy_act", "Naval Supremacy Act");
		policies.put("new_naval_tactis", "New Naval Tactics");
		policies.put("nobility_embassy_act", "Nobility Embassy Act");
		policies.put("noble_loyalty_act", "Noble Loyalty Act");
		policies.put("nobles_in_navy_act", "Noble Naval Traditions");
		policies.put("trained_marines_act", "Organized Marines Act");
		policies.put("overseas_dominions", "Overseas Dominions");
		policies.put("overseas_embassies", "Overseas Embassies");
		policies.put("policy_of_calculate_delay", "Policy of Calculated Delay");
		policies.put("policy_of_neutrality", "Policy of Neutrality");
		policies.put("the_preparation_act", "Preparation Act");
		policies.put("privy_council_establishment_act", "Privy Council Establishment Act");
		policies.put("production_quota_act", "Production Quota Act");
		policies.put("professional_diplomatic_corps", "Professional Diplomatic Corps");
		policies.put("protected_shipping_lanes", "Protected Shipping Lanes Act");
		policies.put("the_provincial_taxation_system", "Provincial Taxation System");
		policies.put("public_legitimacy", "Public legitimacy");
		policies.put("public_welfare_act", "Public Welfare Act");
		policies.put("record_keeping_act", "Recordkeeping Act");
		policies.put("the_recruiting_act", "Recruitment Act");
		policies.put("church_sponsored_guilds", "Religiously Sponsored Guilds");
		policies.put("risk_assessment_policy", "Risk Assessment Policy");
		policies.put("the_royal_commission_act", "Royal Commission Act");
		policies.put("skilled_cartographers", "Skilled Cartographers");
		policies.put("the_spy_discovery_act", "Spy Discovery Act");
		policies.put("the_stamp_act", "Stamp Act");
		policies.put("the_statute_of_monopolies", "Statute of Monopolies");
		policies.put("streamlined_galley_production", "Streamlined Galley Production");
		policies.put("superior_fortification_act", "Superior Fortifications");
		policies.put("superior_supply_system", "Superior Supply Systems");
		policies.put("supply_convoys", "Supply Convoys");
		policies.put("taxation_with_representation", "Taxation with Representation");
		policies.put("the_tenures_abolition_act", "Tenures Abolition Act");
		policies.put("the_wooden_wall", "The Fleet is our Wooden Wall");
		policies.put("pen_rely_on_sword_act", "The Pen Relies on The Sword Act");
		policies.put("the_tolerance_act", "Tolerance Act");
		policies.put("trade_connection_policy", "Trade Connections Policy");
		policies.put("trade_kontor_network", "Trade Kontor Network");
		policies.put("the_transportation_act", "Transportation Act");
		policies.put("underhanded_diplomacy_act", "Underhanded Diplomacy Act");
		policies.put("unified_army_command", "Unified Army Command");
		policies.put("vassal_integration_act", "Vassal Integration Act");
		policies.put("vassal_obligations_act", "Vassal Obligations Act");
		policies.put("vassal_taxation_policy", "Vassal Taxation Policy");
		policies.put("visionary_thinkers", "Visionary Thinkers");
		policies.put("weapon_quality_standards", "Weapon Quality Standards");
		policies.put("the_witchcraft_act", "Witchcraft Act");
		policies.put("zealous_captains", "Zealous Captains");
	}
}
