package eu4SaveReader.Utils;

import java.util.HashMap;

public final class Policies {

    private Policies () {
    }

    public static final HashMap<String, String> policies = new HashMap<>();

    static {
        policies.put("agricultural_cultivations", "Agricultural Cultivation");
        policies.put("anti_heresy_act", "Anti-Heresy Act");
        policies.put("anti_smuggling_act", "Anti-Smuggling Act");
        policies.put("armed_neutrality_act", "Armed Neutrality Act");
        policies.put("autonomous_estates", "Autonomous Estates");
        policies.put("the_banking_system", "Banking System");
        policies.put("beneficial_neglect", "Benign Neglect");
        policies.put("black_chamber_act", "Black Chamber Act");
        policies.put("chaplains_of_the_fleet", "Chaplains of the Fleet");
        policies.put("cloth_quality_edict", "Cloth Quality Edict");
        policies.put("colonial_administration_act", "Colonial Administration Act");
        policies.put("colonial_companies_act", "Colonial Companies Act");
        policies.put("colonial_expansions", "Colonial Expansion");
        policies.put("colonial_garrisons", "Colonial Garrisons");
        policies.put("restrictions_for_colonies", "Colonial Restrictions");
        policies.put("the_combination_act", "Combination Act");
        policies.put("commercial_embassies", "Commercial Embassies");
        policies.put("the_cooperation_act", "Cooperation Act");
        policies.put("the_court_of_wards_and_liveries", "Court of Wards and Liveries");
        policies.put("cultural_recognition_act", "Cultural Recognition Act");
        policies.put("cultural_understanding", "Cultural Understanding");
        policies.put("cultural_unity", "Cultural Unity");
        policies.put("deserteur_act", "Deserter Act");
        policies.put("diplomatic_cooperation_act", "Diplomatic Cooperation");
        policies.put("diplomatic_defence_act", "Diplomatic Defense Act");
        policies.put("the_dissolution_act", "Dissolution Act");
        policies.put("edict_of_expulsion", "Edict of Expulsion");
        policies.put("the_education_act", "Education Act");
        policies.put("encouragement_of_merchant_navy", "Encouragement of Merchant Navy");
        policies.put("enforce_religious_law", "Enforce Religious Law");
        policies.put("enlightened_aristocracy", "Enlightened Aristocracy");
        policies.put("the_espionage_act", "Espionage Act");
        policies.put("exchange_of_ideas", "Exchange of Ideas");
        policies.put("the_field_agent_act", "Field Agent Act");
        policies.put("field_priests", "Field priests and Soldier's prayer books");
        policies.put("fleet_surgeons", "Fleet Surgeons");
        policies.put("foreign_advisors", "Foreign Advisors");
        policies.put("the_foreign_aid_act", "Foreign Aid Act");
        policies.put("the_foreign_support_act", "Foreign Support Act");
        policies.put("formalized_measures", "Formalized Scales, Weights and Measures");
        policies.put("fortified_trading_posts", "Fortified Trading Posts");
        policies.put("full_sovereignty_act", "Full Sovereignty Act");
        policies.put("the_garrison_act", "Garrison System");
        policies.put("guerilla_warfare", "Guerilla Warfare");
        policies.put("harbour_administration", "Harbor Administration");
        policies.put("hired_adventurers_act", "Hired Adventurers");
        policies.put("horse_artillery", "Horse Artillery");
        policies.put("the_importation_act", "Importation Act");
        policies.put("inspirational_leaders", "Inspirational Leaders");
        policies.put("the_integrated_administration_act", "Integrated Administration Act");
        policies.put("land_inheritance_act", "Land Inheritance Act");
        policies.put("letters_of_marque", "Letters of Marque");
        policies.put("the_liberation_act", "Liberation Act");
        policies.put("the_licensing_of_the_press_act", "Licensing of the Press Act");
        policies.put("the_liquor_act", "Liquor Act");
        policies.put("local_army_organisation", "Local Army Organization");
        policies.put("local_militias", "Local Militias");
        policies.put("manueline_architecture", "Manueline Architecture");
        policies.put("the_mercenary_registration_act", "Mercenary Registration Act");
        policies.put("messenger_ships", "Messenger Ships");
        policies.put("military_zeal_act", "Military Zeal Act");
        policies.put("the_mining_act", "Mining Act");
        policies.put("modern_firearm_techniques", "Modern Firearm Techniques");
        policies.put("modern_siege_weapons", "Modern Siege Weapons");
        policies.put("multilingual_diplomats", "Multilingual Diplomats");
        policies.put("native_assimilation_act", "Native Assimilation Act");
        policies.put("the_nautic_education_act", "Nautical Education Act");
        policies.put("convoy_system", "Naval Convoy System");
        policies.put("naval_infrastructure_act", "Naval Infrastructure");
        policies.put("the_naval_inspection_act", "Naval Inspection Act");
        policies.put("naval_school_act", "Naval School Act");
        policies.put("naval_secrecy_act", "Naval Secrecy Act");
        policies.put("the_naval_supremacy_act", "Naval Supremacy Act");
        policies.put("new_naval_tactis", "New Naval Tactics");
        policies.put("nobility_embassy_act", "Nobility Embassy Act");
        policies.put("noble_loyalty_act", "Noble Loyalty Act");
        policies.put("nobles_in_navy_act", "Noble Naval Traditions");
        policies.put("trained_marines_act", "Organized Marines Act");
        policies.put("overseas_dominions", "Overseas Dominions");
        policies.put("overseas_embassies", "Overseas Embassies");
        policies.put("policy_of_calculate_delay", "Policy of Calculated Delay");
        policies.put("policy_of_neutrality", "Policy of Neutrality");
        policies.put("the_preparation_act", "Preparation Act");
        policies.put("privy_council_establishment_act", "Privy Council Establishment Act");
        policies.put("production_quota_act", "Production Quota Act");
        policies.put("professional_diplomatic_corps", "Professional Diplomatic Corps");
        policies.put("protected_shipping_lanes", "Protected Shipping Lanes Act");
        policies.put("the_provincial_taxation_system", "Provincial Taxation System");
        policies.put("public_legitimacy", "Public legitimacy");
        policies.put("public_welfare_act", "Public Welfare Act");
        policies.put("record_keeping_act", "Recordkeeping Act");
        policies.put("the_recruiting_act", "Recruitment Act");
        policies.put("church_sponsored_guilds", "Religiously Sponsored Guilds");
        policies.put("risk_assessment_policy", "Risk Assessment Policy");
        policies.put("the_royal_commission_act", "Royal Commission Act");
        policies.put("skilled_cartographers", "Skilled Cartographers");
        policies.put("the_spy_discovery_act", "Spy Discovery Act");
        policies.put("the_stamp_act", "Stamp Act");
        policies.put("the_statute_of_monopolies", "Statute of Monopolies");
        policies.put("streamlined_galley_production", "Streamlined Galley Production");
        policies.put("superior_fortification_act", "Superior Fortifications");
        policies.put("superior_supply_system", "Superior Supply Systems");
        policies.put("supply_convoys", "Supply Convoys");
        policies.put("taxation_with_representation", "Taxation with Representation");
        policies.put("the_tenures_abolition_act", "Tenures Abolition Act");
        policies.put("the_wooden_wall", "The Fleet is our Wooden Wall");
        policies.put("pen_rely_on_sword_act", "The Pen Relies on The Sword Act");
        policies.put("the_tolerance_act", "Tolerance Act");
        policies.put("trade_connection_policy", "Trade Connections Policy");
        policies.put("trade_kontor_network", "Trade Kontor Network");
        policies.put("the_transportation_act", "Transportation Act");
        policies.put("underhanded_diplomacy_act", "Underhanded Diplomacy Act");
        policies.put("unified_army_command", "Unified Army Command");
        policies.put("vassal_integration_act", "Vassal Integration Act");
        policies.put("vassal_obligations_act", "Vassal Obligations Act");
        policies.put("vassal_taxation_policy", "Vassal Taxation Policy");
        policies.put("visionary_thinkers", "Visionary Thinkers");
        policies.put("weapon_quality_standards", "Weapon Quality Standards");
        policies.put("the_witchcraft_act", "Witchcraft Act");
        policies.put("zealous_captains", "Zealous Captains");
    }

    public static final HashMap<String, String> policiesFR = new HashMap<>();

    static {
        policiesFR.put("agricultural_cultivations", "Cultures agronomiques");
        policiesFR.put("anti_heresy_act", "Loi contre l'hérésie");
        policiesFR.put("anti_smuggling_act", "Loi contre la contrebande");
        policiesFR.put("armed_neutrality_act", "Loi de neutralité armée");
        policiesFR.put("autonomous_estates", "États autonomes");
        policiesFR.put("beneficial_neglect", "Négligence bienveillante");
        policiesFR.put("black_chamber_act", "Loi sur le Cabinet noir");
        policiesFR.put("chaplains_of_the_fleet", "Aumôniers de la marine");
        policiesFR.put("church_sponsored_guilds", "Commandes religieuses aux guildes");
        policiesFR.put("cloth_quality_edict", "Édit sur la qualité des draps");
        policiesFR.put("colonial_administration_act", "Loi sur l'administration coloniale");
        policiesFR.put("colonial_companies_act", "Loi sur les compagnies coloniales");
        policiesFR.put("colonial_expansions", "Expansion coloniale");
        policiesFR.put("colonial_garrisons", "Garnisons coloniales");
        policiesFR.put("commercial_embassies", "Ambassades commerciales");
        policiesFR.put("convoy_system", "Convois navals");
        policiesFR.put("cultural_recognition_act", "Loi sur la reconnaissance culturelle");
        policiesFR.put("cultural_understanding", "Compréhension culturelle");
        policiesFR.put("cultural_unity", "Unité culturelle");
        policiesFR.put("deserteur_act", "Loi sur les déserteurs");
        policiesFR.put("diplomatic_cooperation_act", "Coopération diplomatique");
        policiesFR.put("diplomatic_defence_act", "Loi de défense diplomatique");
        policiesFR.put("edict_of_expulsion", "Édit d'expulsion");
        policiesFR.put("encouragement_of_merchant_navy", "Encouragement à la marine marchande");
        policiesFR.put("enforce_religious_law", "Loi religieuse");
        policiesFR.put("enlightened_aristocracy", "Noblesse éclairée");
        policiesFR.put("exchange_of_ideas", "Échanges d'idées");
        policiesFR.put("field_priests", "Prêtres militaires et livres de prière des soldats");
        policiesFR.put("fleet_surgeons", "Chirurgiens de marine");
        policiesFR.put("foreign_advisors", "Conseillers étrangers");
        policiesFR.put("formalized_measures", "Échelles, poids et mesures harmonisés");
        policiesFR.put("fortified_trading_posts", "Comptoirs fortifiés");
        policiesFR.put("full_sovereignty_act", "Loi sur la pleine souveraineté");
        policiesFR.put("guerilla_warfare", "Guérilla");
        policiesFR.put("harbour_administration", "Administration des ports");
        policiesFR.put("hired_adventurers_act", "Aventuriers soldés");
        policiesFR.put("horse_artillery", "Artillerie montée");
        policiesFR.put("inspirational_leaders", "Chefs charismatiques");
        policiesFR.put("land_inheritance_act", "Loi sur l'héritage foncier");
        policiesFR.put("letters_of_marque", "Lettres de marque");
        policiesFR.put("local_army_organisation", "Organisation de l'armée locale");
        policiesFR.put("local_militias", "Milices locales");
        policiesFR.put("manueline_architecture", "Architecture manuéline");
        policiesFR.put("messenger_ships", "Navires messagers");
        policiesFR.put("military_zeal_act", "Loi sur la bravoure militaire");
        policiesFR.put("modern_firearm_techniques", "Armes à feu modernes");
        policiesFR.put("modern_siege_weapons", "Armes de siège modernes");
        policiesFR.put("multilingual_diplomats", "Diplomates multilingues");
        policiesFR.put("native_assimilation_act", "Loi sur l'assimilation des indigènes");
        policiesFR.put("naval_infrastructure_act", "Infrastructures navales");
        policiesFR.put("naval_school_act", "Loi sur les Écoles de marine");
        policiesFR.put("naval_secrecy_act", "Loi du secret maritime");
        policiesFR.put("new_naval_tactis", "Nouvelles tactiques navales");
        policiesFR.put("nobility_embassy_act", "Ambassades nobles");
        policiesFR.put("noble_loyalty_act", "Loi sur la fidélité de la noblesse");
        policiesFR.put("nobles_in_navy_act", "Traditions navales de la noblesse");
        policiesFR.put("overseas_dominions", "Possessions d'outre-mer");
        policiesFR.put("overseas_embassies", "Ambassades outre-mer");
        policiesFR.put("pen_rely_on_sword_act", "La plume et l'épée");
        policiesFR.put("policy_of_calculate_delay", "Retards calculés");
        policiesFR.put("policy_of_neutrality", "Neutralité");
        policiesFR.put("privy_council_establishment_act", "Loi sur le Conseil privé");
        policiesFR.put("production_quota_act", "Loi sur les quotas de production");
        policiesFR.put("professional_diplomatic_corps", "Corps diplomatique professionnel");
        policiesFR.put("protected_shipping_lanes", "Loi sur la protection des couloirs maritimes");
        policiesFR.put("public_legitimacy", "Légitimité publique");
        policiesFR.put("public_welfare_act", "Loi du bien public");
        policiesFR.put("record_keeping_act", "Loi sur les rapports");
        policiesFR.put("restrictions_for_colonies", "Restrictions coloniales");
        policiesFR.put("risk_assessment_policy", "Évaluation des risques");
        policiesFR.put("skilled_cartographers", "Cartographes de talent");
        policiesFR.put("streamlined_galley_production", "Production rationalisée de galères");
        policiesFR.put("superior_fortification_act", "Fortifications améliorées");
        policiesFR.put("superior_supply_system", "Logistique améliorée");
        policiesFR.put("supply_convoys", "Convois de ravitaillement");
        policiesFR.put("taxation_with_representation", "Taxation donc représentation");
        policiesFR.put("the_banking_system", "Système bancaire");
        policiesFR.put("the_combination_act", "Loi sur les corporations");
        policiesFR.put("the_cooperation_act", "Loi sur la coopération");
        policiesFR.put("the_court_of_wards_and_liveries", "Tribunal des minorités et livrées");
        policiesFR.put("the_dissolution_act", "Loi sur la dissolution");
        policiesFR.put("the_education_act", "Loi sur l'éducation");
        policiesFR.put("the_espionage_act", "Loi sur l'espionnage");
        policiesFR.put("the_field_agent_act", "Agents sur le terrain");
        policiesFR.put("the_foreign_aid_act", "Loi sur l'aide étrangère");
        policiesFR.put("the_foreign_support_act", "Loi de soutien étranger");
        policiesFR.put("the_garrison_act", "Système de garnisons");
        policiesFR.put("the_importation_act", "Loi sur les importations");
        policiesFR.put("the_integrated_administration_act", "Loi sur l'intégration de l'administration");
        policiesFR.put("the_liberation_act", "Loi sur la libération");
        policiesFR.put("the_licensing_of_the_press_act", "Loi sur les licences de la presse");
        policiesFR.put("the_liquor_act", "Loi sur les alcools");
        policiesFR.put("the_mercenary_registration_act", "Loi sur le rôle des mercenaires");
        policiesFR.put("the_mining_act", "Loi sur les mines");
        policiesFR.put("the_nautic_education_act", "Loi sur l'éducation maritime");
        policiesFR.put("the_naval_inspection_act", "Loi sur l'inspection des navires");
        policiesFR.put("the_naval_supremacy_act", "Loi sur la suprématie navale");
        policiesFR.put("the_preparation_act", "Loi sur la préparation");
        policiesFR.put("the_provincial_taxation_system", "Système d'imposition provincial");
        policiesFR.put("the_recruiting_act", "Loi sur le recrutement");
        policiesFR.put("the_royal_commission_act", "Loi sur les commissions d'enquête");
        policiesFR.put("the_spy_discovery_act", "Loi sur la découverte des espions");
        policiesFR.put("the_stamp_act", "Loi sur les timbres");
        policiesFR.put("the_statute_of_monopolies", "Statut des monopoles");
        policiesFR.put("the_tenures_abolition_act", "Loi sur l'abolition des tenures");
        policiesFR.put("the_tolerance_act", "Loi de tolérance");
        policiesFR.put("the_transportation_act", "Loi sur les marchandises");
        policiesFR.put("the_witchcraft_act", "Loi sur la sorcellerie");
        policiesFR.put("the_wooden_wall", "La flotte est notre rempart de chêne");
        policiesFR.put("trade_connection_policy", "Relations commerciales");
        policiesFR.put("trade_kontor_network", "Réseau de comptoirs commerciaux");
        policiesFR.put("trained_marines_act", "Loi sur l'infanterie de marine");
        policiesFR.put("underhanded_diplomacy_act", "Loi sur les « cadeaux » diplomatiques");
        policiesFR.put("unified_army_command", "État-major centralisé");
        policiesFR.put("vassal_integration_act", "Loi sur l'intégration des vassaux");
        policiesFR.put("vassal_obligations_act", "Loi sur les obligations vassaliques");
        policiesFR.put("vassal_taxation_policy", "Taxation des vassaux");
        policiesFR.put("visionary_thinkers", "Penseurs visionnaires");
        policiesFR.put("weapon_quality_standards", "Armes de qualité standardisées");
        policiesFR.put("zealous_captains", "Capitaines zélés");
    }
}
